name: pueblito_viajero
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_statusbarcolor_ns: ^0.5.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^0.8.7+3
  permission_handler: ^10.2.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  fl_chart: ^0.68.0
  image: ^3.0.1
  path_provider: ^2.0.11
  table_calendar: ^3.1.2
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.3+2
  flutter_map: ^7.0.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
